# Setup
title: "nihilistkitten"
tagline: "we're all stories in the end; just make it a good one"
description: "Hi! I'm Riley. My pronouns are they/them. I suppose this site is one of many ways in which I scream into the void."
url: "localhost:4000"
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Riley Shahar
  url: https://nihilistkitten.me
  email: riley.shahar@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version: 1.1.0
